# Generated by Django 4.2.1 on 2023-06-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={},
        ),
    ]
