# Generated by Django 4.2.1 on 2023-06-02 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_alter_offers_options_alter_skills_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_size', models.IntegerField()),
                ('company_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.AlterModelOptions(
            name='brandsoffice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employmenttypes',
            options={},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='skills',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='offer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='chart.offers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.brands'),
        ),
    ]
