# Generated by Django 4.2.1 on 2023-06-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_brands_alter_brandsoffice_options_and_more'),
    ]

    operations = [
    ]
