# Generated by Django 4.2.1 on 2023-06-02 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20230602_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttypes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.date(2023, 6, 2), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandsoffice',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.brands'),
        ),
        migrations.AlterField(
            model_name='brandsoffice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brandsoffice',
            name='slug',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='employmenttypes',
            name='employment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.offers'),
        ),
    ]
