# Generated by Django 4.2.1 on 2023-06-03 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_employmenttypes_id_alter_brandsoffice_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='offer',
            new_name='offer_id',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='id',
        ),
        migrations.RemoveField(
            model_name='brandsoffice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employmenttypes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='id',
        ),
        migrations.AddField(
            model_name='brands',
            name='brand_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandsoffice',
            name='office_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenttypes',
            name='employment_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
