# Generated by Django 4.2.1 on 2023-06-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_rename_offer_skills_offer_id_remove_skills_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offer',
            new_name='offer_id',
        ),
    ]
