# Generated by Django 4.2.1 on 2023-06-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_rename_offer_offers_offer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='offer_id',
            new_name='skill_id',
        ),
    ]
