# Generated by Django 4.2.1 on 2023-06-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0014_rename_offer_id_skills_skill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_id',
            new_name='skill',
        ),
    ]
