# Generated by Django 4.2.1 on 2023-06-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0016_remove_skills_id_alter_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill',
            new_name='skill_id',
        ),
    ]
