# Generated by Django 4.2.1 on 2023-06-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0017_rename_skill_skills_skill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skill_id',
            new_name='id',
        ),
    ]
