# Generated by Django 4.2.1 on 2023-06-05 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0019_remove_brands_brand_alter_brands_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsoffice',
            name='brand_office',
        ),
        migrations.RemoveField(
            model_name='employmenttypes',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employmenttypes',
            name='offer',
        ),
        migrations.AddField(
            model_name='brandsoffice',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenttypes',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandsoffice',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='brandsoffice',
            name='slug',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
